### ISSUE TITLE
Log start and end time of each run for troubleshooting purposes

### ISSUE THREAD

**Issue by marco-m** [concourse/s3-resource#109]
## What challenge are you facing?

I have a classic job that builds code and uploads the artifacts with the S3 resource. Normally it takes 6 minutes for the full job (build + S3 upload/download). Sometimes it takes 1h30!

When trying to troubleshoot, one can see the timestamps of the build task, but not the timestamps of the S3 task.

Consider this job:

![missing-timestamps](https://user-images.githubusercontent.com/3075069/47225019-4c77cf00-d3bd-11e8-831a-33f1323ce42f.png)

and imagine that instead than 16s it took 1h30, with each parallel build task taking 5 minutes each. I want to know where the remaining 1h25 of time went.

The build task have a timestamp, while the S3 resource not. The only thing I know from the S3 resource is, looking at the speed and the size, the time it took. It could very well be that they took 1 minute each, and all the delays are in the scheduling of the tasks and the streaming of the artifacts from the non-Linux workers to a Linux worker which runs the S3 task.

What is missing is a timestamp; knowing the duration is not enough.

If I am not looking at the build while it is in progress (classic example: I am a Concourse operator and the team owning the pipeline informs me after the build finished that it took an abnormal amount of time), it is impossible for me to understand where the slowdown happened.

If on the other hand each single task associated to a Concourse resource were to log their start and stop time, I could at least pinpoint in which phase of the job sequence there is a problem, allowing me to focus my troubleshooting in a specific area.

## What would make this better?

Ideally, the ATC should print the start time of the scheduling of each task, and each worker should print the start time of the starting of each task. This in the web UI, not only in the debug log. This would add only 2 text lines per task and would make the life of operators way better.

## Are you interested in implementing this yourself?

Yes. I will provide a PR that does something less global but still better than nothing: the S3 resource will print when it starts and when it finishes.

**Comment by marco-m** [comment]
The proposed change looks like

![s3-print-start-finish](https://user-images.githubusercontent.com/3075069/47370586-60397300-d6e6-11e8-9b3e-ad63654a0eb2.png)

**Comment by vito** [comment]
Can this and #110 be closed now that https://github.com/concourse/concourse/pull/3579 is in? :thinking:

**Comment by marco-m** [comment]
@vito I see your reasoning for the closing. The main difference is that concourse/concourse#3579, although a GREAT improvement, displays durations, not timestamps. Durations can still hide tens of minutes of idleness. On the other hand, I want to be pragmatic. Let's close and see how duration alone fares.

**Comment by vito** [comment]
Thanks. :slightly_smiling_face: 

FWIW the duration is derived from timestamps so maybe there could be some other way to reveal those. :thinking:
