### ISSUE TITLE
S3 Resource doesn't utilize AWS S3's Multipart feature for large uploads/downloads

### ISSUE THREAD

**Issue by Kaixiang** [concourse/s3-resource#12]
AWS has a feature for faster uploads of a single large file using [Multipart uploads](http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html). This is a problem when uploading large release tarballs to S3. Would be great if the s3 resource could be smart and decide what type of upload to use for what type of file.

**Comment by vito** [comment]
Try with 0.64; we switched S3 libraries and I'm pretty sure it does this now. (I think it actually did before too.)
