### ISSUE TITLE
Glob documentation inaccurate; does not follow Bash

### ISSUE THREAD

**Issue by JamesHagerman** [concourse/s3-resource#121]
The line `The matching syntax is bash glob expansion, so no capture groups, etc.` in the `README.md` is incorrect. There is no way to do glob exclusion in the file attribute using this resource despite it being well supported by bash.

Under the hood, this resource uses Go's `filepath.Glob()` function. `Glob()` uses the same syntax as `Match()` which is documented [here](https://golang.org/pkg/path/filepath/#Match). Because Match doesn't support exclusion, neither does this resource.

For example: Let's try selecting `thing@0.0.1.zip` from a directory containing these files:
```
thing@0.0.1.zip
thing@0.0.1+stuff.zip
thing@0.0.1+stuff.morestuff.zip
```

This is the relevant part of the s3 resource:
```
- name: s3-upload
  type: s3
  source:
    regexp: thing@(.*).zip
```

And this is the task in a Concourse job with the glob:
```
- put: s3-upload
  params:
    file: thing@!(*+stuff.zip|*+stuff.morestuff.zip)
```

This will return an error in the format of `error running command: no matches found for pattern:`

All of these patterns should match as well but also throw errors:
```
thing!(*+*.zip)
thing@!(*+*.zip)
thing@!(*+*)
```

Attempting to run `shopt -s extglob` in the container doesn't improve the situation.

Another issue brought up the idea of replacing the filename glob with regex but was rejected because globs were "good enough". As this filename format is in line with (Semver build metadata conventions[(https://semver.org/#spec-item-10), it would be great for Concourse to support something that can gracefully handle those cases.

While the pattern `thing@?????[^+]*` could work, it will fail as soon as any of the versions enter double digits.

Am I missing something? Is there a clean way to do this using the current implementation?

If nothing else, please update the docs to not reference bash globbing.

**Comment by vito** [comment]
I'm guessing moving the singular file to its own separate output isn't possible (or is too janky).

> If nothing else, please update the docs to not reference bash globbing.

Happy to review a PR for this, or a PR to add support for `regexp` since this does indeed seem to be a tricky use case.
