### ISSUE TITLE
Infinite discovering any new versions when resource version pinned

### ISSUE THREAD

**Issue by fiftin** [concourse/s3-resource#125]
Concourse v5.0.1

**Actions:**
* Pin one of the old version of S3 resource
* Run task which use this resource

**Expected:**

Old version of S3 resource used

**Actual:**

Infinite state "discovering any new versions of s3-resource"

![image](https://user-images.githubusercontent.com/914224/55471209-ad6d2980-5622-11e9-9643-14bde7724340.png)

**Comment by vito** [comment]
How are you 'picking' the old version? Have you run `fly check-resource` to discover it?

**Comment by fiftin** [comment]
![image](https://user-images.githubusercontent.com/914224/55494488-4b2d1c80-5654-11e9-8728-440f4632dc66.png)

**Comment by vito** [comment]
And has that pinned version made it through all of the upstream jobs? The build preparation message mentions `passed` constraints.

**Comment by fiftin** [comment]
Yes, this build (s3-resource) already successful deployed (task) earlier.

I pinned last version of the resource. Similar behavior - discovering new versions.

**Comment by vito** [comment]
If you expand the version, can you confirm via the succeeded builds that all passed constraints are satisfied?

**Comment by fiftin** [comment]
Looks like problem with `regexp`. Some files from other resource catched by the resource. I fixed `regexp` and now it works fine.
