### ISSUE TITLE
regex does not match provided version

### ISSUE THREAD

**Issue by donkeybrains** [concourse/s3-resource#126]
Hi Guys

Running this with concourse pushing to Octopus.

Tried everything, the config is right for the regex to work error I get: 
error running command: regex does not match provided version: s3resource.Version{Path:"myfilename.1.0.0-ci-1559305944-master-a406f1e.nupkg", VersionID:""}

 name: ceph
  type: s3
  source:
    bucket: some-bucket
    access_key_id: someaccesskey
    secret_access_key: somekey
    endpoint: someendpoint
    regexp: "myfilename.(.*).nupkg"
    skip_ssl_verification: true
    use_v2_signing: true
    region_name: eu-west-1

Im aware of all characters after the major.minor.patch numbers should match [0-9A-Za-z-]

Any ideas good luck.

**Comment by donkeybrains** [comment]
Right the issue here is that my pipeline regex is being ignored.  I have been renaming the c# solution after creating it. So I rename the package,sh octo id and rename the regex to match, push then rebuild, to find it fails.  So I reinstated the package.sh to old version, add a regex that I know doesnt exist, it passes and I get a concourse green pass.  

Does it cache the pipeline.yml I wonder.

**Comment by vito** [comment]
Hi - we use issues for feature requests and bug reports, but this looks more like a support request/question - please consider using our [forums](https://discuss.concourse-ci.org) instead.

**Comment by pratikbin** [comment]
@donkeybrains Facing this same. Even is matching in get step. Any luck?

**Comment by pidement** [comment]
I had the same error. After a lot of wasted time I realized that the regex was wrong.
