### ISSUE TITLE
Uploading file actually uploads every directory?

### ISSUE THREAD

**Issue by RyanKramer** [concourse/s3-resource#128]
I am using a versioned file and specifying the file to override (which is versioned) and yet my job still uploads all of the directories and their contents. It also looks like it does download as well? Which does not make any sense.

**Comment by vito** [comment]
I don't think this resource even *supports* uploading entire directories. Could you show what you're seeing and paste your config?

**Comment by RyanKramer** [comment]
I found that it was a custom image instead of the one to be intended. Thank you for the quick response but I'll go ahead and close this issue.
