### ISSUE TITLE
How do you promote via get / put?

### ISSUE THREAD

**Issue by sean-abbott** [concourse/s3-resource#132]
I want to promote an artifact from my staging s3 bucket to my production s3 bucket.

Hypothetically, the job should just be a get with staging resource and a put with the production resource (since they sue different creds)

But I can't get it to find it.

Do I actually have to run a task to copy from one folder to another? Because that seems....

**Comment by vito** [comment]
What have you tried?

FWIW: we use issues for feature requests and bug reports, but this looks more like a support request/question - please consider using our [forums](https://discuss.concourse-ci.org) instead.

**Comment by sean-abbott** [comment]
I think it's a feature request 'cause it doesn't seem to have the feature. I run a task to copy at this point. Feel free to close, though, since I have something working.
