### ISSUE TITLE
Access s3 without hardcoding IAM secret key and access key

### ISSUE THREAD

**Issue by gvoden** [concourse/s3-resource#162]
Hi,

we are trying to access s3 resource without the need to explicitly specify access_key_id and secret_access_key in the s3 resource definition (we commit pipeline definitions to our Azure DevOps git and do not want to expose any credentials).
Concourse runs on EC2 server which has access through s3 by assuming its instance role/instance profile.

Currently we get "access denied" even though the role attached to EC2 has access to s3. This means that Concourse itself is unable to implicitly assume a role.

thanks for your help!

**Comment by taylorsilva** [comment]
Realized this is a similar ask as #151 so closing this issue. Re-open if there is a difference I'm missing here.
