### ISSUE TITLE
AWS SDK can panic when retrieving files that are not chunked

### ISSUE THREAD

**Issue by krobertson** [concourse/s3-resource#17]
This is mostly to cross reference aws/aws-sdk-go#417.

On smaller files, S3 may not return the `Content-Range` header if it did not chunk the response. In the AWS SDK, it was accessing the ContentRange value (a `*string`) without any nil checks and it was causing a panic when the `put` step does a get after doing the upload.

This caused a huge rash of 20+ build failures for us over the weekend. I have a patch that I'll be submitting upstream, but wanted to filed this issue to highlight it so you can pull in the latest SDK once it is merged.

The panic output was:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x531305]

goroutine 7 [running]:
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).setTotalBytes(0xc820096380, 0xc8201360e0)
    /tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:206 +0x95
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).downloadPart(0xc820096380, 0xc8200146c0)
    /tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:175 +0x46a
created by github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download
    /tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:114 +0xbe
```

**Comment by sclevine** [comment]
+1

(Lattice pipeline is currently unusable without patching the S3 resource.)

**Comment by vito** [comment]
Thanks for submitting the patch upstream, we'll pull it in ASAP.

**Comment by philpennock** [comment]
Fixed upstream: https://github.com/aws/aws-sdk-go/commit/2c52a85d66d65f0e85b991839d7513b2e2cbc71b

**Comment by krobertson** [comment]
Here I hadn't had a chance to post mine because I hadn't added tests yet, and their fix doesn't include any tests. But now they access ContentLength without checking if it is nil. :)

**Comment by longnguyen11288** [comment]
thanks @krobertson for image! ran into it myself

**Comment by oppegard** [comment]
+1 for pulling in the patch ASAP. We're seeing this error a lot more in the past few days.

**Comment by vito** [comment]
@krobertson seems pretty unlikely for content-length to be nil at least, so we'll pull in their patch as it is so far

**Comment by krobertson** [comment]
This is one place where the AWSK SDK seems odd.  Their response object is different from `http.Response`. In normal Go, `ContentLength` is not nullable. However with the AWS SDK, on their response object it is.  It may be unlikely it is nil, however what is the chance S3 sends a chunked response or anything?

It is likely safe, but I still hope they do the right thing upstream. I may still just send my patch because checking ContentLength is pretty easy, and far rather see total bytes of 0 than have an app panic. I'm old fashioned. :smile:
