### ISSUE TITLE
Support S3 compatible / custom endpoint URL?

### ISSUE THREAD

**Issue by JamesClonk** [concourse/s3-resource#2]
Would it be possible to add support for S3 compatible endpoints?
Currently there seems to be no way to specify a custom endpoint URL.

Something along the lines of this:
```go
if endpointURL != "" {
    region = aws.Region{S3Endpoint: endpointURL}
}
...
s3.New(auth, region)
```
?

**Comment by vito** [comment]
Seems doable. Would you mind submitting a PR?

**Comment by JamesClonk** [comment]
OK, I gave it a try: concourse/s3-resource/pull/3
Cheers!
