### ISSUE TITLE
Feature suggestion: initial resource version & content

### ISSUE THREAD

**Issue by bleach** [concourse/s3-resource#21]
We are using a S3 bucket to hold state for terraform, which we share between jobs and we've been using the S3 resource to do this.

The first job in the pipeline that uses terraform state, needs to both consume the S3 resource (to read existing state) and write out its modified state.

When runnning the pipeline for the first time, the state is empty and the bucket 
contains no matching object. In our situation what we'd actually like to do is 
for the resource to return an inital, low numbered, version and some user-defined empty content.

In order to do this we were thinking of adding two bits of configuration:
- `initial_version`: Optional. If present, when there's no object in the bucket, this would be returned as the only version.
- `initial_content`: Optional. If present, when there's no matching object in the S3 bucket, this content will be placed in `filename`.

We'd probably need to check that if `initial_version` was set, then `initial_content` was also set and vice versa.

Before going away and writing the code to do this, we wanted to check that feature was something you would consider for inclusion. Also, we're relatively new to concourse and if there's a better way of passing state between jobs than using resources, that would be good to know.

**Comment by dcarley** [comment]
Any feedback on this? We're happy to schedule the work, but need to know if the design seems correct and is suitable for merging upstream.

**Comment by xoebus** [comment]
Yep, sorry for the delay.

This sounds good! We'd like to merge something like this. @vito mentioned that in the long term this may point to a missing CloudFormation/Terraform resource but in the short term this is a good solution. :+1:

**Comment by DanielJonesEB** [comment]
@bleach We've been feeling the need for this too - we'd been thinking of an "allow empty" flag for the S3 resource so it still fires with a version for a file that doesn't exist, rather than default content. We'd then create that content in a task... Use case is generating credentials.

Lemme know if you've got anywhere with yours!

**Comment by jtarchie** [comment]
@dcarley && @bleach, the interface is sound, but would you ever need one without the other? An initial version would have some content and some content would still require a version. An initial version makes more sense to me.

**Comment by DanielJonesEB** [comment]
We've been feeling the need for "fire on non-existent file" more and more - typically when trying to create idempotent pipelines, where things like credentials and SSL certs are generated.

I'm thinking two modes of operation:
1. When no files are matched, emit one static, never-changing version
2. When no files are matched, emit a new version number

The former would be useful for when you only want this to happen once, and the latter for whenever a file is missing (in case its deletion is part of the object's lifecycle).

Does this sound like utter madness? Are we going about this the wrong way?

**Comment by jtarchie** [comment]
@DanielJonesEB, why do you need the file from s3 before it has been generated?

**Comment by DanielJonesEB** [comment]
@jtarchie If the file does not exist, no version is emitted, and no job fires as a result. So we want a job that can create things if they don't exist, and no-op if they do.

**Comment by archgrove** [comment]
A +1 for the use case of @DanielJonesEB; we're having a very similar problem. S3 is acting as a cache for a build process; we want a job that checks the input file to see if it's up to date, and replaces it if not. As a job will never fire on a missing S3 resource, we're having to manually seed the bucket with a dummy file.

**Comment by vito** [comment]
Merged #99!
