### ISSUE TITLE
Example configuration uses deprecated syntax

### ISSUE THREAD

**Issue by njbennett** [concourse/s3-resource#24]
The example plan configuration below-- 
```
- put: release
  params:
    from: a/release/path/release-(.*).tgz
```
-- uses the "from" parameter, which is deprecated. Because of this, it was not clear to us that this syntax was deprecated. It should be updated to use the "file" syntax.

Also, it was difficult for us to understand what format the file path should be written in-- whether it was a regexp or a glob or something else entirely. We had a number of problems uploading files to an S3 bucket, and there was a long period where weren't sure if we weren't creating the file in question correctly, or if we weren't referring to it correctly in the Resource/Plan configuration. More explicit guidance on this point in the documentation would have helped us solve this problem faster and with less direct assistance from the Concourse team.

**Comment by vito** [comment]
fixed the example; thanks for the issue
