### ISSUE TITLE
Unclear how to specify how to map container's directory structure to S3 destination directory structure

### ISSUE THREAD

**Issue by cjcjameson** [concourse/s3-resource#25]
Hi there,

Based on the changes in v0.68, we now see that `put`s to/from syntax has been deprecated. After some digging and looking at the example that you provided in [the issue here](https://github.com/concourse/s3-resource/issues/19), we see that the resource definition's `regexp` field needs to contain an foldername if you want the artifact to end up within a folder.

Can you please clarify in the readme exactly how to achieve the following:
I have a file in the output of a job: `my_folder/my_file.1.2.3.tgz`
I want to put all files that match the following regex in that output to an s3 resource: `my_folder/my_file.*.tgz`
I want them to end up in the folder `my_files` on the s3 bucket.

It is our understanding that we should specify the following `regexp` property on the s3 resource definition: `my_files/my_file.*.tgz`
and the `file` property of the `put` to the s3 resource should be: `my_folder/my_file.*.tgz`

If this understanding is correct we believe that the readme is unclear and could be updated to better demonstrate this functionality.

Thanks!

C.J. and Zak

**Comment by vito** [comment]
thinkin this is resolved now with that PR
