### ISSUE TITLE
Add option to ignore self-signed cert validation

### ISSUE THREAD

**Issue by sparameswaran** [concourse/s3-resource#28]
When using Riak-CS as S3 compatible resource and the service is using self-signed certs, verification fails.
```
Error: error running command: RequestError: send request failed
caused by: Post https://s3.pez.pivotal.io/asfdasdf?uploads=: 
x509: certificate signed by unknown authority
```
Will help having an option to ignore/handle self-signed certs.

**Comment by vito** [comment]
This is there as `disable_ssl`.
