### ISSUE TITLE
Only works with us Standard region not with other

### ISSUE THREAD

**Issue by amulyas** [concourse/s3-resource#29]
I have a resource defined like this 
- name: pipeline-version
  type: semver
  source:
    bucket: {{aws-pipeline-bucket}}
    key: pipeline-version
    initial_version: 0.1.0
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region: us-west-2

I created my bucket in us-west-2 

was getting 
resource script '/opt/resource/check []' failed: exit status 1
stderr:
error checking for new versions: Get : 301 response missing Location header

so it was not passing the region correctly to s3 request 

only when bucket is in US Standard it works as it default to us-east-1
https://github.com/concourse/s3-resource/blob/9b39d518283368260128292d8309da489b1f148e/s3client.go#L59-61

**Comment by kirederik** [comment]
You should set the `region_name` property (in your resource configuration, you are using `region`).
