### ISSUE TITLE
 The difference between the request time and the current time is too large when uploading to s3 bucket

### ISSUE THREAD

**Issue by jianqiu** [concourse/s3-resource#34]
I encountered the following problem frequently when uploading resource to s3 bucket.

391.52 MB / 391.52 MB [============================] 100.00 % 404.10 KB/s 16m32s
error running command: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
	upload id: YAsz7CGh5S5KTL_FJVCp5VQ8pe8C01qQNpCad8ZouTfARLqVVzz28oXpoCEzd_IIqdU4EJKEbVKzxY_kMDfKUA--

**Comment by vito** [comment]
Is your worker's clock in sync? (ntp?)

**Comment by mattcui** [comment]
@vito yes, it's synced, we ran the following commands in worker:

```
service ntp stop
ntpdate -s 0.amazon.pool.ntp.org
service ntp start
```

We found the problem only occurred when trying to upload a "big" file onto S3, for examples:
```
391.49 MB / 391.49 MB [============================] 100.00 % 404.16 KB/s 16m31serror running command: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
```
There took 16m31s, I suspect if there is a bug in s3 resource or in S3 API, seems it compared the time of starting the upload to the end time, it took more than 15 mins. Is it possible? Thanks.

**Comment by mattcui** [comment]
@vito Do you think if it might be a bug in S3 resource type when transferring a "bigger" package, spending more than 15 mins? Thanks.

**Comment by vito** [comment]
Could be. That's a fairly common failure mode for authenticated uploads.

**Comment by vito** [comment]
This looks like a tricky problem to avoid, but one thing that may help is parallel, chunked uploads. We have code in place to do this, but I think the progress rendering got in the way:

https://github.com/concourse/s3-resource/blob/master/s3client.go#L155

We wrap `Body` with a progress-emitting `io.Reader`. The `s3manager` performs parallel uploads by trying to cast `Body` to `io.Seeker` and `io.ReaderAt`, which this progress-wrapped reader doesn't support. This the upload happens in series, increasing the likelihood for a single long-running request that may hit this error.

I'll prioritize a fix for this; we should probably wrap the body with an object that implements the methods that allow it to still be uploaded in parallel.

**Comment by mattcui** [comment]
Thanks, @vito . we are willing to try with the new fix, so please let us know when it's available. Thanks. @jianqiu @maximilien

**Comment by JeffMuniz** [comment]
Guys please help, here at htis url you may see https://www.pivotaltracker.com/n/projects/1059262/stories/119803371/comments/137771301

"zachgersh made a PR to update the aws sdk, and now uploading large files works even if they take half an hour to upload:"

How do I can get this file/script/solution?

**Comment by maximilien** [comment]
Can you add link to PR? Not listed on the Tracker story. Thx

**Comment by spnkr** [comment]
Running `sudo ntpdate ntp.ubuntu.com` on the server fixed this for me.

**Comment by awanmbandi** [comment]
> @vito yes, it's synced, we ran the following commands in worker:
> 
> ```
> service ntp stop
> ntpdate -s 0.amazon.pool.ntp.org
> service ntp start
> ```
> 
> We found the problem only occurred when trying to upload a "big" file onto S3, for examples:
> 
> ```
> 391.49 MB / 391.49 MB [============================] 100.00 % 404.16 KB/s 16m31serror running command: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
> ```
> 
> There took 16m31s, I suspect if there is a bug in s3 resource or in S3 API, seems it compared the time of starting the upload to the end time, it took more than 15 mins. Is it possible? Thanks.

Awsome 

> @vito yes, it's synced, we ran the following commands in worker:
> 
> ```
> service ntp stop
> ntpdate -s 0.amazon.pool.ntp.org
> service ntp start
> ```
> 
> We found the problem only occurred when trying to upload a "big" file onto S3, for examples:
> 
> ```
> 391.49 MB / 391.49 MB [============================] 100.00 % 404.16 KB/s 16m31serror running command: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
> ```
> 
> There took 16m31s, I suspect if there is a bug in s3 resource or in S3 API, seems it compared the time of starting the upload to the end time, it took more than 15 mins. Is it possible? Thanks.

Awesome man, this works like boom :)
