### ISSUE TITLE
Support EC2 IAM Role SessionToken

### ISSUE THREAD

**Issue by mweagle** [concourse/s3-resource#37]
I'm using IAM Roles for EC2 security credentials. In trying to use the `S3` resource, it looks as though the [SessionToken](http://docs.aws.amazon.com/sdk-for-go/api/aws/credentials.html) must also be set.  Just using the _AccessKeyID_ and _SecretAccessKey_ values results in an error.

I didn't see a way to provide the SessionToken to [NewStaticCredentials](https://github.com/concourse/s3-resource/blob/master/s3client.go#L70). 

Related: https://github.com/concourse/semver-resource/issues/16

**Comment by vito** [comment]
Thinking of closing this and https://github.com/concourse/semver-resource/issues/16 in favor of https://github.com/concourse/concourse/issues/291 - in lieu of Vault's support for IAM roles: https://github.com/hashicorp/vault/issues/307

**Comment by mweagle** [comment]
Hi @vito - I agree that using something like Vault would be a good way to standardize key management. Would this be transparent to me as an AWS IAM Role user, or an additional piece of infrastructure I'd need to manage?  Thanks for the follow up.

**Comment by vito** [comment]
Vault is a server you'd need to deploy, and I imagine you'd just give its EC2 instance the necessary IAM roles. Admittedly we haven't explored it enough yet for me to give you more solid answers, but we'll be starting on it in the coming week.

**Comment by mweagle** [comment]
Sounds good - looking forward to what you find out. Thanks again.

**Comment by fquirce** [comment]
hi @vito, this is a quite simple ticket that will benefit the people that uses IAM roles a lot.
Why not doing it if it takes a few hours and the vault secrets option looks nice but this is easier and is a quick win. thanks

**Comment by vito** [comment]
@fquirce I understand it can be frustrating, but I'm opposed to merging in things that are going against Concourse's intended direction so long as we have the correct direction planned. There's no real reason for anyone to be blocked on us merging this in given that you can just override the `s3` resource type with your own in your pipeline.

**Comment by vito** [comment]
Closing per what I mentioned before - we should at least consolidate discussion in to #291, which so far has no one talking about IAM roles.

**Comment by willejs** [comment]
@vito can you consider opening this back up? IAM roles are really useful, whilst using vault would be ideal, It is not desirable to use it in every use case.
