### ISSUE TITLE
Loading the "private" field with fly -v quotes "true" and breaks resource

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/s3-resource#41]
Due to this concourse issue: https://github.com/concourse/concourse/issues/360

**Comment by xtreme-gavin-enns** [comment]
Could this be addressed for this specific case internal to the s3 resource? It seems like it should be simple (although inelegant) to allow for quoted booleans in addition to proper json booleans

**Comment by vito** [comment]
Yes, this should be fixed by the s3 resource, since it's the only thing that knows it's a bool.

**Comment by vito** [comment]
Change of pace: there's a proposal for new params behavior, which should fix this. See https://github.com/concourse/concourse/issues/545. Closing this one issue so we can just keep track of that; thanks!
