### ISSUE TITLE
Add an element that puts the full url of an uploaded resource into the clipboard

### ISSUE THREAD

**Issue by zrob** [concourse/s3-resource#45]
We use this resource for archiving log files.  When we need to pull a specific log it would be nice to get a full download url instead of just the filename.

**Comment by vito** [comment]
It should be there in the metadata already. Granted, you have to select the text and copy-paste manually, but once we do auto-linking (https://github.com/concourse/concourse/issues/429) it'd just be right-click -> copy url. Does that sound good enough?

**Comment by zrob** [comment]
@vito I'm not seeing a full url, just a filename on v2.1.0.

Also I wasn't as clear about what I was asking for as I could have been.  Having a link I can copy from the resource page would be good.  Having the link appear in the task that uploads a file for a job that I need logs for would be great.

**Comment by vito** [comment]
Here's what I'm talking about - it should be in the metadata:

![screenshot from 2016-10-08 11-12-48](https://cloud.githubusercontent.com/assets/1880/19215066/3c563bba-8d48-11e6-8449-95a54de1233d.png)
![screenshot from 2016-10-08 11-13-05](https://cloud.githubusercontent.com/assets/1880/19215067/3c56a122-8d48-11e6-9c1b-a053cc4ee2f6.png)

**Comment by zrob** [comment]
Weird I see this, maybe I've got a stale version or a config issue or something:

![image](https://cloud.githubusercontent.com/assets/1703742/19215156/4228d608-8d4b-11e6-94b2-1287e1ac0d3c.png)

My ask is actually to see it here since getting to a version based on looking at a failed job is my normal use case:

![image](https://cloud.githubusercontent.com/assets/1703742/19215161/5a231fa2-8d4b-11e6-8d74-2116785cc385.png)

**Comment by vito** [comment]
huh, weird. latest concourse version? no custom resource types or anything?
