### ISSUE TITLE
Naming of "private" flag is confusing (low-priority, docs)

### ISSUE THREAD

**Issue by cjcjameson** [concourse/s3-resource#47]
We see that if we set "private" on the resource definition, all the urls we get are signed. Signing the URLs actually makes them *more* public, in a way. Without signing, if the bucket is private, you can only access it with proper IAM credentials. With signing, a "public" consumer has a credentialed way to get at them. For our current use case, that's the feature we actually want! We have a legacy CI system that needs to consume Concourse outputs but doesn't have AWS credentials. But the naming is throwing us off.

Maybe this is just a README change, maybe a deprecation and new flag.

**Comment by amilkh** [comment]
Also, the default validity of the signed AWS URL is 24 hours and is hardcoded deep in the s3 resource. If we could have this parametrized that would be great!

**Comment by cjcjameson** [comment]
Heads up: there may be an undesirable behavior where Baggage Claim can't assure that the signed S3 URL that it serves up is valid any more. See https://github.com/concourse/concourse/issues/622 for one proposed feature that would maybe help alleviate it. But otherwise, it's going to get hairy.

Concourse is great at properly versioned items; for S3, the `url` file that comes along for the ride is fine, but outside the umbrella of versioning. So there's no way to handle it in the Concourse idiom.

**Comment by vito** [comment]
Related to the findings in https://github.com/concourse/concourse/issues/622 - URL signing should probably be done with `put` instead, which will be a good opportunity to pick a better name. (`private` should remain supported for backwards-compatibility).

Opened https://github.com/concourse/s3-resource/issues/53 to express this.
