### ISSUE TITLE
Unable to get the s3 resource to point to my own s3 server

### ISSUE THREAD

**Issue by jonathanmaw** [concourse/s3-resource#5]
Hi,

I have an s3 server running on my computer, concourse running inside a bosh-lite VM on the same computer.
I do not know how to specify "endpoint" or "cloudfront_url" in such a way as to communicate with that server (via ip address).
I suspect "endpoint" is the wrong way to go about it, as that generates a URL of the format "https://<bucket>.<endpoint>", which will not suit my needs.
In attempting to use cloudfront_url, though, it appears to be ignored, and when attempting to "put", I get `error running command: 403: "The AWS Access Key Id you provided does not exist in our records."`

My first guess was that I was unable to reach the s3 server, and it was falling back to amazon, but I was able to make a task that could ping the server.

When I added "endpoint" to the resource's configuration, it then started using that (leading to error messages like `error running command: Post https://s3_test_artifacts.10.24.1.174:10453/test-0.0.1.tar.gz?uploads: dial tcp: lookup s3_test_artifacts.10.24.1.174: no such host`), which surprised me, given from what I've read of the source code suggests cloudfront_url takes precedence.

However, I have not been able to identify whether the s3 resource I have running on my VM (hence deployed via bosh) has the same source code.

Any help on how to identify what's causing this problem for me, or how to identify what the version of the s3-resource I am running is would be appreciated.

Regards,

Jonathan

**Comment by xoebus** [comment]
You may be able to use a service such as http://xip.io in order to route to your local IP address. That will let the subdomain resolve properly and you may be able to avoid the need to fiddle with the CloudFront stuff at all?
