### ISSUE TITLE
Output directory when fetch files from S3

### ISSUE THREAD

**Issue by beeva-carlosleon** [concourse/s3-resource#60]
Hi,

We don't know if its possible to configure a output directory in get operations inside the pipeline.

The reason is that we need to use the file stored in S3 to copy in a dockerfile (using add or copy directives), and it's necessary to have in a subdirectory from dockerfile path.

Thanks in advance!

**Comment by chendrix** [comment]
Hi there! Unfortunately, this is not possible directly with the s3-resource.

We think that people should be using tasks to move around artifacts from their standard locations given via resources.

I'm going to close this. Please feel free to reopen the issue or contact us in [slack](https://slack.concourse.ci)
