### ISSUE TITLE
Use the default credentials for the aws client

### ISSUE THREAD

**Issue by robbruce** [concourse/s3-resource#65]
By default, the aws client will use a credential provider chain to discover authentication. If a user doesn't specify an access key id and secret access key then the defaults should be left alone. Currently the defaults are set to credentials.AnonymousCredentials

https://github.com/concourse/s3-resource/blob/master/s3client.go#L87

Details on the provider chain: https://github.com/aws/aws-sdk-go/blob/b2dc98bb584e48b0f5f39c93110633173c5da43c/aws/config.go#L38

This would mean that if the worker is an EC2 instance, then the IAM Profile associated with the instance could be used.

**Comment by mariash** [comment]
please see my comment here why is this considered to be anti-pattern: https://github.com/concourse/concourse/issues/976#issuecomment-309150218

**Comment by jtarchie** [comment]
I'm closing this for having explicit over implicit behaviour.
