### ISSUE TITLE
The resource does not offer a way to trust a private CA

### ISSUE THREAD

**Issue by DRuggeri** [concourse/s3-resource#71]
Other than the option "disable_ssl" which has no effect on the AWS client regarding certificate trust, there appears to be no way to add trusted CAs to the client. This means it appears to be impossible to trust an internal S3 compatible storage endpoint signed by a private CA.

**Comment by chendrix** [comment]
Closing as captured by concourse/concourse#1027

**Comment by DRuggeri** [comment]
Hi, Chris
I was in the process of writing a patch for s3-resource to address this shortcoming. Can you help me understand if this would not be welcome? I agree that the right thing to do is solve the underlying issue in concourse/concourse#1027, but given the long-running nature of that issue and the fact that a solution hasn't been finalized yet, I wonder if users have a path forward in the near term.
It sucks to add the capability to the resource and perpetuate the problem further... but it at least gets those stuck a path forward. Thoughts welcome.

**Comment by chendrix** [comment]
I would certainly entertain a temporary patch for this as a PR, but I don't want to leave stories in the backlog that we know are going to be subsumed by some other initiative.
