### ISSUE TITLE
`put` fails when `cloudfront_url` specified

### ISSUE THREAD

**Issue by mingxiao** [concourse/s3-resource#73]
When specifying the `cloudfront_url` parameter, a `put` to that resource fails with

```
error running command: Forbidden: Forbidden
	status code: 403, request id: 
```

Our cloudfront distribution does have `Query String Forwarding and Caching` set to `Forward all, cache based on all`.

We hijacked into the container and ran `cat config.json | /opt/resource/in /tmp` with `config.json` containing `{"source":{...}, "version":{"path":"path_to_file_in_s3_bucket"}}`. This failed when the `cloudfront_url` key was present.

**Comment by jtarchie** [comment]
@mingxiao, are you able to provide anymore information? Like manually doing this operation using the `aws` CLI.

A *403* implies that this is an operation not allowed. I don't know if we can work around this issue.

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
