### ISSUE TITLE
Out progress bar is incorrect

### ISSUE THREAD

**Issue by krishicks** [concourse/s3-resource#76]
Given a large file being put to Minio with s3-resource, I see the following:

```
9.21 GB / 9.21 GB [======================================] 100.00 % 4.45 TB/s 0s
```

The reason for this is because the progress reader is incremented when the file to be uploaded is seeked in, rather than when bytes are actually read. The S3 client goes out of its way to use concurrency to upload the file as quickly as possible, and in doing so actually seeks the entire file quickly and immediately before even attempting to upload it.

I looked at the code change that would be necessary to fix this, and it's a bit more than I wanted to take on at this time.

Briefly, [this](https://github.com/concourse/s3-resource/blob/master/progress_reader_at.go#L25) should be moved down into the `ReadAt` function below. However, in doing just that you'll note that while the progress now tracks the actual upload of the file, it actually ends up reading 200%. This is again because of how the AWS S3 client works.

For now I think it's best to remove the incorrect progress bar and come up with a real solution later on. Otherwise it's just wildly incorrect.

I noticed this while uploading to a local Minio server, and I'm not sure if that makes it a special case or not.

**Comment by vito** [comment]
should be fixed by the PR, thanks!

**Comment by krishicks** [comment]
👌
