### ISSUE TITLE
Possible to use without access key?

### ISSUE THREAD

**Issue by cjohansen** [concourse/s3-resource#80]
The docs specify that the access key id and secret are required. Yet, in the source, it looks like the resource will use anonymous credentials if they are missing. We are running Concourse on AWS, and would like to use Roles to govern access. I tried setting up the required role and use the bucket resource with no access key id/secret, but it didn't work.

First of all this is a question: Is it possible to use the bucket resource without an access keypair, and govern access with server Roles? If not, is this something you'd consider accepting a patch to support?

**Comment by jtarchie** [comment]
We don't support this. This issue has been [closed](https://github.com/concourse/s3-resource/pull/22) for the reasons @vito describe.

See also https://github.com/concourse/concourse/wiki/Anti-Patterns#contributor-burden and https://github.com/concourse/concourse/wiki/Anti-Patterns#worker-state

**Comment by cjohansen** [comment]
So if I understand this right you also don't intend to support instance profiles in any other way?

**Comment by jtarchie** [comment]
Nope.

**Comment by cjohansen** [comment]
For anyone else coming here with the same use case there is this: https://github.com/18F/s3-resource-simple
