### ISSUE TITLE
Is there way to allow runtime credentials on S3 resource?

### ISSUE THREAD

**Issue by akoranne** [concourse/s3-resource#89]
The S3 resource requires the creds (access key, secret key) to be passed in. 

A client of mine needs an air-gap environment on a public cloud - gov instance. I know it sounds oxymoronic, but I can assure you, it is a valid case. We are using S3 as image store (no docker). The client also is very strict on security. 

We had to modify the pipelines "assume role" on the fly. We also modified pipelines to use S3 for images (cflinuxfs2, ert etc). It works. 

One caveat though, we still have to provide access key, and secret key in the params that allows access to the S3 bucket which includes the bucket to hold terraform state. Passing these creds are against the client's security procedures. 

So, was wondering, if there is a way to not pass the creds on S3 resource but leverage it at runtime?

**Comment by hunan-rostomyan** [comment]
You can set up a credentials manager (e.g. [CredHub](https://docs.cloudfoundry.org/credhub/), [Vault](https://www.vaultproject.io/)) and store the parameters there to be injected at runtime. This [tutorial](https://concoursetutorial.com/basics/secret-parameters/) explains how to do it with CredHub. 

Request for a Vault tutorial has been created on the tutorial github page, so you might also want to follow that [issue](https://github.com/starkandwayne/concourse-tutorial/issues/129) for updates.
