### ISSUE TITLE
support `version` in params for `get`

### ISSUE THREAD

**Issue by EugenMayer** [concourse/s3-resource#90]
I am trying to get a specific version from the `s3-resource` - that version comes from an `semver-resource`.

```
      - get: candidate-code-version
        passed: [candidate-artifact, candidate-translations]
      - get: candidate-artifact-translations-storage
        version: candidate-code-version/version
```

What i get though, is not the right version:
![image](https://user-images.githubusercontent.com/136934/33834394-192dea42-de83-11e7-8aba-223c0f7fde18.png)

Looking at https://github.com/concourse/s3-resource/blob/master/in/models.go#L7 and https://github.com/concourse/s3-resource/blob/master/check/models.go#L7 i would have expected this to be desired. Am i wrong?

**Comment by EugenMayer** [comment]
Interesting, when i push this pipeline defintion or get the pipeline, i see:

```
    - get: candidate-artifact-translations-storage
      version: null
```

So `version: candidate-code-version/version` is not applied at all.

**Comment by EugenMayer** [comment]
digging a little deeper, seems like the in command supporting the version to be passed as expected https://github.com/concourse/s3-resource/blob/master/in/in_command.go#L26 - but thats by protocol when considering that check always retrieves the version to be used for `get`.

That means i have to look at check more then on `in` thus

https://github.com/concourse/s3-resource/blob/master/check/check_command.go#L32

It seems like https://github.com/concourse/s3-resource/blob/master/check/check_command.go#L41 does only supporting the retrieve the version dynamically, so the most recent one. For that topic, i think a might have found a bug ( it seems to retrieve latest-1 in my case). But thats just a different topic.

Is there any plan to support a param for in, overriding the version given by check?
 - otherwise i returns this version as the one to pick up by in. 

My scenario is:

 - i cannot use `passed` for the translation resource, since its not part of the same pipeline
 - i have a job, running before, creating the translations using the release-candidate version to write into the very same s3 bucket
 - now i want to package the "application package" and the translations, both referenced by its release-candidate versions
 
Any thoughts? I could provide a PR for that

**Comment by EugenMayer** [comment]
Just got pointed by @vito to http://concourse.ci/get-step.html#get-step-version .. but that would actually mean, that https://github.com/concourse/s3-resource/issues/90#issuecomment-350731415 is something we do not want for sure?

**Comment by scottschulthess** [comment]
This is pretty much my use case as well - I want to be able to grab a specific file/version from s3

**Comment by scottschulthess** [comment]
appears to work if you do this ```  
- get: 
   version: {path: "something.txt"}
``` suggest we close this ticket

**Comment by scottschulthess** [comment]
Or even 
```
params:
  version: {path: "savannah-2.10.4.tgz"}
```

**Comment by pms1969** [comment]
@scottschulthess I don't see this working as it stands.  I'm on Concourse 3.9.2, and passing the version file to the `get` just ends up spinning.

```
-get: version
- get: s3-resource-thingy
  version: {path: "version/version"}
```

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/684 - this is out of scope for any particular resource, and would require a core Concourse feature.
